
cities = [
    "New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego",
    "Dallas", "San Jose", "Austin", "Jacksonville", "Fort Worth", "Columbus", "San Francisco", "Charlotte",
    "Indianapolis", "Seattle", "Denver", "Washington", "Boston", "El Paso", "Nashville", "Detroit",
    "Oklahoma City", "Portland", "Las Vegas", "Memphis", "Louisville", "Baltimore", "Milwaukee", "Albuquerque",
    "Tucson", "Fresno", "Mesa", "Sacramento", "Atlanta", "Kansas City", "Colorado Springs", "Miami",
    "Raleigh", "Omaha", "Long Beach", "Virginia Beach", "Oakland", "Minneapolis", "Tulsa", "Arlington",
    "Tampa", "New Orleans", "Wichita", "Cleveland", "Bakersfield", "Aurora", "Anaheim", "Honolulu",
    "Santa Ana", "Riverside", "Corpus Christi", "Lexington", "Stockton", "St. Louis", "St. Paul",
    "Henderson", "Pittsburgh", "Cincinnati", "Anchorage", "Greensboro", "Plano", "Newark", "Lincoln",
    "Orlando", "Irvine", "Toledo", "Jersey City", "Chula Vista", "Durham", "Fort Wayne", "St. Petersburg",
    "Laredo", "Buffalo", "Madison", "Lubbock", "Chandler", "Scottsdale", "Glendale", "Reno", "Norfolk",
    "Winston-Salem", "North Las Vegas", "Irving", "Garland", "Hialeah", "Gilbert", "Fremont", "Boise"
]
flight_companies = [
    "American Airlines",
    "Delta Air Lines",
    "United Airlines",
    "Southwest Airlines",
    "Alaska Airlines",
    "JetBlue Airways",
    "Spirit Airlines",
    "Frontier Airlines",
    "Allegiant Air",
    "Hawaiian Airlines",
    "Sun Country Airlines",
    "SkyWest Airlines",
    "Mesa Airlines",
    "Republic Airways",
    "Endeavor Air",
    "Envoy Air",
    "PSA Airlines",
    "Atlas Air",
    "Polar Air Cargo",
    "Southern Air",
    "Kalitta Air",
    "ABX Air",
    "Amerijet International",
    "National Airlines",
    "World Atlantic Airlines",
    "Miami Air International",
    "Alaska Seaplanes",
    "Cape Air",
    "Contour Airlines",
    "Elite Airways",
    "Gulfstream International Airlines",
    "Island Air",
    "Northern Air Cargo",
    "PenAir",
    "Ravn Alaska",
    "Ravn Connect",
    "Republic Airline",
    "Silver Airways",
    "Tradewind Aviation",
    "Ultimate Air Shuttle",
    "Western Global Airlines",
    "XTRA Airways",
    "Boutique Air",
    "GrandView Aviation",
    "Linear Air",
    "Maya Island Air",
    "Southern Airways Express",
]
rental_car_companies = [
    "Velocity Rentals",
    "Horizon Cars",
    "StarDrive Rentals",
    "UrbanWheels",
    "Skyline Autos",
    "RapidRide Rent-a-Car",
    "CityCruise Rentals",
    "EliteDrive Car Hire",
    "MetroWheels",
    "PrimeRent",
    "DriveLux",
    "Summit Car Rentals",
    "InfiniteDrive",
    "Prestige Wheels",
    "ExpressRent",
    "UrbanChariots",
    "ProDrive Rentals",
    "LuxeCar Hire",
    "TurboRide",
    "CapitalDrive",
    "SilverWings Car Rental",
    "SwiftFleet Rentals",
    "SkyHigh Drives",
    "Presto Cars",
    "MetroMile Rent-a-Car",
    "DriveSmart",
    "Pinnacle Rentals",
    "CloudCars",
    "SunRise Auto Rentals",
    "VelocityRide",
    "DreamDrive Car Hire",
    "Galaxy Autos",
    "Zenith Rentals",
    "Quantum Drives",
    "CrystalCar Hire",
    "Apex Wheels",
    "Cascade Car Rentals",
    "ThriveDrive",
    "Visionary Autos",
    "SummitStar Rent-a-Car"
]
us_car_brands = [
    "Chevrolet",
    "Ford",
    "Toyota",
    "Honda",
    "Nissan",
    "Jeep",
    "Ram",
    "Hyundai",
    "GMC",
    "Subaru",
    "Volkswagen",
    "Mazda",
    "BMW",
    "Mercedes-Benz",
    "Kia",
    "Buick",
    "Audi",
    "Lexus",
    "Acura",
    "Cadillac",
    "Chrysler",
    "Dodge",
    "Tesla",
    "Volvo",
    "Infiniti",
    "Jaguar",
    "Land Rover",
    "Mitsubishi",
    "Porsche",
    "Genesis",
    "Lincoln",
    "Mini",
    "Fiat",
    "Alfa Romeo",
    "Bentley",
    "Ferrari",
    "Maserati",
    "McLaren",
    "Rolls-Royce",
    "Smart",
    "Bugatti",
    "Karma",
    "Lucid Motors",
    "Rivian",
    "Lordstown Motors",
    "Rivian",
    "Lucid Motors",
    "Nikola"
]
car_type = ['hatchback', 'sedan', 'SUV', 'Truck', 'Coupe', 'OffRoad', 'MiniVan', 'Convertible', 'Wagon', 'Luxury', 'Electric', 'Hybrid', 'Sports Car', 'Minivan', 'Crossover']

